---
title: "MuxViz"
author: "Miguel Jacome"
date: "14/5/2018"
output: html_document
---

```{r Data Frame}
coord<-read.csv("/Users/apple/Desktop/Palmito/Doctorado Spatial Analysis/Bases de datos/Coordenadas palmitos/Archivos coordenadas completas/coord_net.csv")
#mart <- add_rownames(mart, "plant") #naming the first column

#fruits per record multiplex
fruits_record<-read.csv("~/Desktop/Palmito/Postdoc-Interaction Networks/C.-humilis-Fugivorous-Networks/Interaction Motifs/Fruits_record.csv")
```

```{r Matrix reshped}
#Multiplying by the probability of recruitment
rabbit_weight=0.286
rat_weight=0.286
fox_weight=0.179
badger_weight=0.179
wildb_weight=0
deer_weight=0.0112

mart_matas_rec <-mutate(fruits_record,
    #Resize effects
    rabbit = rabbit * rabbit_weight,
    rat = rat * rat_weight,
    fox = fox * fox_weight,
    badger = badger * badger_weight,
    wildboar= wildboar * wildb_weight,
    deer=deer*deer_weight)



#mean of recruitment plant
fruits_record["mean_rec"]<-apply(mart_matas_rec[,2:6],1,mean)
mart_matas_rec["mean_rec"]<-apply(mart_matas_rec[,2:6],1,mean)
fruits_record["deer_a"]<-fruits_record$deer-mart_matas_rec$deer
fruits_record["deer_m"]<-mart_matas_rec$deer

mart_rec<-subset(mart_matas_rec[47:70,])
matas_rec<-subset(mart_matas_rec[1:46,])

apply(mart_matas_rec[,2:6],2,mean)

#Martinazo
mart_mux<-subset(fruits_record[47:70,])
mart_mux["node_plant"]<-1:24
mart_mux<-mart_mux[,c(11,9,10,3,4,5,6,7,8,1)]

mart_mux1<-mart_rec
mart_mux1["node_plant"]<-1:24
mart_mux1<-mart_mux1[,c(9,2,3,4,5,6,7,8,1)]


#Mean effectiveness of frugivores
apply(mart_rec[,2:7],2,mean)

#Matasgordas
matas_mux<-subset(fruits_record[1:46,])
matas_mux["node_plant"]<-1:46
matas_mux<-matas_mux[,c(11,9,10,3,4,5,6,7,8,1)]

matas_mux1<-matas_rec
matas_mux1["node_plant"]<-1:46
matas_mux1<-matas_mux1[,c(9,2,3,4,5,6,7,8,1)]

#Mean effectiveness of frugivores
apply(matas_rec[,2:7],2,mean)


```

```{r Modifying data}

#Martinazo
mart_mux_lomg<-melt(mart_mux,id.vars="node_plant")
mart_mux_lomg<-mutate(mart_mux_lomg,node_animal = if_else( variable == "deer_a","25",if_else(variable == "deer_m", "25", if_else(variable == "wildboar", "26", if_else( variable == "rabbit","27", if_else( variable == "rat","28", if_else( variable == "fox","29", if_else(variable == "badger", "30", "ERROR" ))))))))


mart_mux_lomg<-mutate(mart_mux_lomg,node_Layer = if_else( node_animal == "25","1", if_else(node_animal == "26", "1", if_else( node_animal == "27","2", if_else( node_animal == "28","2", if_else( node_animal == "29","2", if_else(node_animal == "30", "2", "ERROR" )))))))


mart_mux_lomg1<-melt(mart_mux1,id.vars="node_plant")
mart_mux_lomg1<-mutate(mart_mux_lomg1,node_animal = if_else( variable == "deer","25", if_else(variable == "wildboar", "26", if_else( variable == "rabbit","27", if_else( variable == "rat","28", if_else( variable == "fox","29", if_else(variable == "badger", "30", "ERROR" )))))))
mart_mux_lomg1<-mutate(mart_mux_lomg1,node_Layer = if_else( node_animal == "25","1", if_else(node_animal == "26", "1", if_else( node_animal == "27","2", if_else( node_animal == "28","2", if_else( node_animal == "29","2", if_else(node_animal == "30", "2", "ERROR" )))))))


write.table(mart_mux_lomg, "/Users/apple/desktop/Palmito/Postdoc-Interaction_Networks/C.-humilis-Fugivorous-Networks/muxViz-master/data/Multilayer_mart_2/multi_mart_new.txt", col.names = FALSE, row.names = FALSE, sep = " ")


#Bipartite d3

mart_mux_lomg<-melt(mart_mux,id.vars="plant")
columns<-c("Primary","Secondary","Frugivory")
colnames(mart_mux_lomg)<-columns

bipartite_D3(mart_mux_lomg, filename = "maritd3_frug",PrimaryLab = "Plant", SecondaryLab = "Animal", SiteNames = "Martinazo",colouroption = c("brewer"))

mart_mux_lomg_eff<-melt(mart_mux1,id.vars="plant")
columns<-c("Primary","Secondary","Frugivory")
colnames(mart_mux_lomg_eff)<-columns

bipartite_D3(mart_mux_lomg_eff, filename = "martid3_eff",PrimaryLab = "Plant", SecondaryLab = "Animal", SiteNames = "Martinazo",colouroption = c("brewer"))

#two webs
doublewbs<-mart_mux_lomg 
doublewbs["efficency"]<-mart_mux_lomg_eff$Frugivory
process<-c("Frugivory", "Seed dispersal")

bipartite_D3(doublewbs, filename = "martid3_frg_eff",PrimaryLab = "Plant", SecondaryLab = "Animal", SiteNames = process,colouroption = c("brewer"))



#Matasgordas
mata_mux_lomg<-melt(matas_mux,id.vars="node_plant")
mata_mux_lomg<-mutate(mata_mux_lomg,node_animal = if_else(variable == "deer_a","32", if_else(variable == "deer_m","32", if_else(variable== "wildboar", "33", if_else( variable == "rabbit","34", if_else( variable == "rat","35", if_else( variable == "fox","36", if_else(variable == "badger", "37", "ERROR" ))))))))

mata_mux_lomg<-mutate(mata_mux_lomg,node_Layer = if_else( node_animal == "32","1", if_else(node_animal == "33", "1", if_else( node_animal == "34","2", if_else( node_animal == "35","2", if_else( node_animal == "36","2", if_else(node_animal == "37", "2", "ERROR" )))))))

mata_mux_lomg["layer_plant"]<-mata_mux_lomg$node_Layer
mata_mux_lomg<-subset(mata_mux_lomg[,-2])

mata_mux_lomg<-sapply(mata_mux_lomg, as.numeric )
mata_mux_lomg<-mata_mux_lomg[,c(1,5,3,4,2)]

write.table(mata_mux_lomg, "/Users/apple/desktop/Palmito/Postdoc-Interaction Networks/C.-humilis-Fugivorous-Networks/muxViz-master/data/Multilayer_matasgordas/multi_mata.txt", col.names = FALSE, row.names = FALSE, sep = " ")


#eliminating all "0" values in each row
mata_mux_lomg<-mata_mux_lomg[apply(mata_mux_lomg!=0, 1, all),]
write.table(mata_mux_lomg, "/Users/apple/desktop/Palmito/Postdoc-Interaction_Networks/C.-humilis-Fugivorous-Networks/muxViz-master/data/Multilayer_matas_2/multi_mata_new.txt", col.names = FALSE, row.names = FALSE, sep = " ")
```











